
CREATE TABLE AVALIACAO
    (
    CODIGO INT NOT NULL PRIMARY KEY
            GENERATED ALWAYS AS IDENTITY
            (START WITH 1, INCREMENT BY 1),
    NOME_PESSOA VARCHAR(100),
    AVALIACAO   VARCHAR(100),
    COD_TRILHA  INT
    );

CREATE TABLE TRILHAS
(
    CODIGO INT NOT NULL PRIMARY KEY
            GENERATED ALWAYS AS IDENTITY
            (START WITH 1, INCREMENT BY 1),
    NOME_TRILHA VARCHAR(100)
    )

ALTER TABLE AVALIACAO ADD CONSTRAINT TRILHAS_FK
FOREIGN KEY (COD_TRILHA) REFERENCES TRILHAS(CODIGO);

